name: Environment and Secrets

on: 
  workflow_dispatch:

en:
  AWS_REGION: us-east-1
  Environment: production

jobs:
  
  deploy-to-aws:
    runs-on: ubuntu-latest
    
    env:
      DEPLOYMENT_NAME: MyAppDeployment
    
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Print workflow-level environment variables
        run: |
          echo "AWS Region: $AWS_REGION"
          echo "Environment: $Environment"
          echo "Deployment Name: $DEPLOYMENT_NAME"

      - name: Print masked secret
        run: |
          echo "AWS Access Key: ${{ secrets.AWS_ACCESS_KEY_ID }}"
          echo "AWS Secret Key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}"

      - name: set and use step-level environment variable
        run: |
          export STEP_LEVEL_VAR= "StepVariableValue"
          echo "Step Level Variable: $STEP_LEVEL_VAR"
      
      - name: Demonstarte variable scopes
        run: |
          echo "Accessing workflow-level env var: $Environment"
          echo "Accessing job-level env var: $DEPLOYMENT_NAME"
          echo "Accessing step-level env var: $STEP_LEVEL_VAR"
          echo "Secret example (masked): ${{ secrets.AWS_ACCESS_KEY_ID }}"
      